/**
 * Local type definitions extracted from the deleted @canvas/shell package.
 *
 * These were inlined here when packages/canvas-shell was removed from the
 * monorepo.  The shell-integration layer is the only consumer of these types
 * inside apps/web.
 */

import type React from 'react';

/**
 * Abstract card – the fundamental unit of the shell.
 */
export interface CardType {
  id: string;
  title: string;
  position: { x: number; y: number };
  size: { width: number; height: number };
  zIndex: number;
  isMinimized: boolean;
  isFullscreen: boolean;
  pluginId: string;
  pluginData: unknown;
  createdAt: number;
  updatedAt: number;
}

/**
 * Props passed to a plugin's renderBody.
 */
export interface CardBodyProps<TData = unknown> {
  card: CardType;
  pluginData: TData;
  updatePluginData: (data: Partial<TData>) => void;
  isFullscreen: boolean;
  isFocused: boolean;
}

/**
 * Props passed to renderHeaderTitle / renderHeaderActions.
 */
export interface CardHeaderActionsProps<TData = unknown> {
  card: CardType;
  pluginData: TData;
}

/**
 * Parameters for creating a new card (id, zIndex, timestamps generated by shell).
 */
export type CreateCardParams = Omit<CardType, 'id' | 'zIndex' | 'createdAt' | 'updatedAt'>;

/**
 * Imperative handle for the CanvasShell component.
 */
export interface ShellHandle {
  getCards(): CardType[];
  getCard(id: string): CardType | null;
  createCard(params: CreateCardParams & { id?: string }): string;
  updateCard(id: string, updates: Partial<Omit<CardType, 'id' | 'createdAt'>>): void;
  deleteCard(id: string): void;
  organizeCards(options?: { fitToScreen?: boolean; cardWidth?: number; cardHeight?: number }): void;
  undoOrganize(): boolean;
  clearCanvas(): void;
  bringCardToFront(id: string): void;
}

/**
 * Card plugin contract.
 */
export interface CardPlugin<TData = unknown> {
  id: string;
  name: string;
  defaultData?: TData;
  renderContextProvider?: (props: {
    card: CardType;
    pluginData: TData;
    children: React.ReactNode;
  }) => React.ReactNode;
  providesWrapper?: boolean;
  renderBody: (props: CardBodyProps<TData>) => React.ReactNode;
  renderHeaderTitle?: (props: CardHeaderActionsProps<TData>) => React.ReactNode;
  renderHeaderActions?: (props: CardHeaderActionsProps<TData>) => React.ReactNode;
  skipContentPadding?: boolean;
  skipDefaultHeader?: boolean;
  lifecycle?: {
    onCardCreated?: (card: CardType) => void | Promise<void>;
    onCardDestroyed?: (card: CardType) => void | Promise<void>;
    onCardMinimized?: (card: CardType) => void | Promise<void>;
    onCardRestored?: (card: CardType) => void | Promise<void>;
    onCardFullscreenEnter?: (card: CardType) => void | Promise<void>;
    onCardFullscreenExit?: (card: CardType) => void | Promise<void>;
  };
  validateData?: (data: unknown) => data is TData;
}
